export const selectListState = [
  { value: 'alabama', label: 'Alabama' },
  { value: 'alaska', label: 'Alaska' },
  { value: 'arizona', label: 'Arizona' },
  { value: 'arkansas', label: 'Arkansas' },
  { value: 'californie', label: 'Californie' },
  { value: 'caroline du Nord', label: 'Caroline du Nord' },
  { value: 'caroline du Sud', label: 'Caroline du Sud' },
  { value: 'colorado', label: 'Colorado' },
  { value: 'connecticut', label: 'Connecticut' },
  { value: 'dakota du Nord', label: 'Dakota du Nord' },
  { value: 'dakota du Sud', label: 'Dakota du Sud' },
  { value: 'delaware', label: 'Delaware' },
  { value: 'floride', label: 'Floride' },
  { value: 'géorgie', label: 'Géorgie' },
  { value: 'hawaï', label: 'Hawaï' },
  { value: 'idaho', label: 'Idaho' },
  { value: 'illinois', label: 'Illinois' },
  { value: 'indiana', label: 'Indiana' },
  { value: 'iowa', label: 'Iowa' },
  { value: 'kansas', label: 'Kansas' },
  { value: 'Kentucky', label: 'Kentucky' },
  { value: 'louisiane', label: 'Louisiane' },
  { value: 'maine', label: 'Maine' },
  { value: 'maryland', label: 'Maryland' },
  { value: 'massachusetts', label: 'Massachusetts' },
  { value: 'michigan', label: 'Michigan' },
  { value: 'minnesota', label: 'Minnesota' },
  { value: 'mississippi', label: 'Mississippi' },
  { value: 'missouri', label: 'Missouri' },
  { value: 'montana', label: 'Montana' },
  { value: 'nebraska', label: 'Nebraska' },
  { value: 'nevada', label: 'Nevada' },
  { value: 'new Hampshire', label: 'New Hampshire' },
  { value: 'new Jersey', label: 'New Jersey' },
  { value: 'new York', label: 'New York' },
  { value: 'nouveau-Mexique', label: 'Nouveau-Mexique' },
  { value: 'ohio', label: 'Ohio' },
  { value: 'oklahoma', label: 'Oklahoma' },
  { value: 'oregon', label: 'Oregon' },
  { value: 'pennsylvanie', label: 'Pennsylvanie' },
  { value: 'rhode Island', label: 'Rhode Island' },
  { value: 'tennessee', label: 'Tennessee' },
  { value: 'texas', label: 'Texas' },
  { value: 'utah', label: 'Utah' },
  { value: 'vermont', label: 'Vermont' },
  { value: 'virginie', label: 'Virginie' },
  { value: 'virginie-Occidentale', label: 'Virginie-Occidentale' },
  { value: 'washington', label: 'Washington' },
  { value: 'wisconsin', label: 'Wisconsin' },
  { value: 'wyoming', label: 'Wyoming' },
]
